# Generated by Django 6.1.1 on 2026-09-10 17:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color')),
                ('business_line', models.CharField(choices=[('ICON', 'ICON'), ('PRINT', 'PRINT'), ('TECH', 'TECH'), ('EDU', 'EDU'), ('GENERAL', 'General')], default='GENERAL', max_length=20, verbose_name='Línea de negocio')),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Stock actual')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo unitario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('unit', models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('ml', 'Mililitros'), ('L', 'Litros')], default='g', max_length=10, verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Tipo de material',
                'verbose_name_plural': 'Tipos de material',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AlertThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_stock', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Stock mínimo')),
                ('notify_email', models.BooleanField(default=True, verbose_name='Notificar por email')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='threshold', to='inventory.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Umbral de alerta',
                'verbose_name_plural': 'Umbrales de alerta',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='material_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.materialtype', verbose_name='Tipo de material'),
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Cantidad consumida')),
                ('machine', models.CharField(max_length=100, verbose_name='Máquina')),
                ('print_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre de la pieza')),
                ('laminator_data', models.JSONField(blank=True, help_text='Datos crudos del laminador (Bambu Studio / Chitubox)', null=True, verbose_name='Datos del laminador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to='inventory.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Trabajo de impresión',
                'verbose_name_plural': 'Trabajos de impresión',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida')], max_length=3, verbose_name='Tipo de movimiento')),
                ('adjustment_type', models.CharField(choices=[('purchase', 'Compra'), ('print_job', 'Trabajo de impresión'), ('manual_in', 'Ajuste manual (entrada)'), ('manual_out', 'Ajuste manual (salida)'), ('waste', 'Merma/desperdicio')], default='manual_in', max_length=20, verbose_name='Motivo')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Cantidad')),
                ('reference', models.CharField(blank=True, help_text='Ej: Compra #INV-001, Trabajo #001', max_length=100, verbose_name='Referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Movimiento de stock',
                'verbose_name_plural': 'Movimientos de stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('name', 'brand', 'color'), name='unique_material_brand_color'),
        ),
    ]
