# Generated by Django 6.1.1 on 2026-09-17 23:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Ciudad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='printjob',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Campo de compatibilidad; usar items del trabajo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to='inventory.material', verbose_name='Material (legado)'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='quantity_used',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Campo de compatibilidad; el consumo real va en items.', max_digits=10, null=True, verbose_name='Cantidad consumida (legado)'),
        ),
        migrations.CreateModel(
            name='MaterialUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ej: FIL-001, RES-001. Coincide con la etiqueta física.', max_length=20, unique=True, verbose_name='Código / etiqueta QR')),
                ('finish', models.CharField(blank=True, max_length=30, verbose_name='Acabado')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color')),
                ('hex_color', models.CharField(blank=True, help_text='Ej: #1A1A1A (referencia).', max_length=7, verbose_name='Color hexadecimal')),
                ('photo_ref', models.CharField(blank=True, help_text='Ej: fotos/FIL-001.jpg', max_length=200, verbose_name='Referencia de foto')),
                ('gross_weight', models.DecimalField(decimal_places=3, default=0, help_text='Peso actual de la bobina/botella en balanza.', max_digits=10, verbose_name='Peso bruto (g)')),
                ('empty_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Tara: envase vacío (g)')),
                ('density', models.DecimalField(decimal_places=3, default=Decimal('1.10'), help_text='Solo resina. Típico 1.05–1.15.', max_digits=5, verbose_name='Densidad (g/ml)')),
                ('nominal_capacity', models.DecimalField(decimal_places=3, default=Decimal('1000'), help_text='Capacidad de la bobina/botella en la unidad del material.', max_digits=10, verbose_name='Capacidad nominal')),
                ('status', models.CharField(choices=[('nueva', 'Nueva'), ('en_uso', 'En uso'), ('agotada', 'Agotada')], default='nueva', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='inventory.material', verbose_name='Material')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='inventory.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Unidad de material',
                'verbose_name_plural': 'Unidades de material (bobinas/botellas)',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='material_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.materialunit', verbose_name='Unidad (bobina/botella)'),
        ),
        migrations.CreateModel(
            name='PrintJobItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Cantidad consumida')),
                ('material_unit', models.ForeignKey(help_text='Cada ítem registra una bobina/botella usada en el trabajo (cambio de rollo).', on_delete=django.db.models.deletion.PROTECT, related_name='print_items', to='inventory.materialunit', verbose_name='Unidad consumida')),
                ('print_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.printjob', verbose_name='Trabajo')),
            ],
            options={
                'verbose_name': 'Ítem de trabajo',
                'verbose_name_plural': 'Ítems de trabajo',
                'ordering': ['id'],
            },
        ),
    ]
